version: 2.1

jobs:
  backend-lint:
    docker:
      - image: node:18.19.0-alpine3.19
    steps:
      - checkout
      - run:
          name: "Installing Node Modules"
          command: "npm install"
      - run:
          name: "Backend lint"
          working_directory: ./backend
          command: "npm run lint-check"
          
  backend-type-check:
    docker:
      - image: node:18.19.0-alpine3.19
    steps:
      - checkout
      - run:
          name: "Installing Node Modules"
          command: "npm install"
      - run:
          name: "Migrating Database"
          working_directory: ./backend
          command: "npm run db-install"
      - run:
          name: "Backend type check"
          working_directory: ./backend
          command: "npm run type-check"

  backend-unit-tests:
    docker:
      - image: node:18.19.0-alpine3.19
    steps:
      - checkout
      - run:
          name: "Installing Node Modules"
          command: "npm install"
      - run:
          name: "Migrating Database"
          working_directory: ./backend
          command: "npm run db-install"
      - run:
          name: "Backend unit tests"
          working_directory: ./backend
          command: "npm run unit-tests"

workflows:
  backend-ci-workflow:
    jobs:
      - backend-lint
      - backend-type-check
      - backend-unit-tests
